// backend/services/codeFormatter.js

// Get language for syntax highlighting
function getLanguageFromPath(filepath) {
    const ext = filepath.substring(filepath.lastIndexOf('.') + 1).toLowerCase();
    
    const languageMap = {
        'js': 'javascript', 'jsx': 'jsx', 'ts': 'typescript', 'tsx': 'tsx',
        'py': 'python', 'java': 'java', 'go': 'go', 'rs': 'rust',
        'c': 'c', 'cpp': 'cpp', 'h': 'c', 'hpp': 'cpp',
        'cs': 'csharp', 'php': 'php', 'rb': 'ruby', 'html': 'html',
        'htm': 'html', 'css': 'css', 'scss': 'scss', 'json': 'json',
        'xml': 'xml', 'yaml': 'yaml', 'yml': 'yaml', 'md': 'markdown',
        'sql': 'sql', 'sh': 'bash', 'bash': 'bash'
    };
    
    return languageMap[ext] || 'plaintext';
}

// Generate directory tree
export function generateDirectoryTree(files) {
    const tree = {};
    
    for (const file of files) {
        const parts = file.path.split('/');
        let current = tree;
        for (let i = 0; i < parts.length; i++) {
            const part = parts[i];
            if (i === parts.length - 1) {
                current[part] = null;
            } else {
                if (!current[part]) current[part] = {};
                current = current[part];
            }
        }
    }
    
    function renderTree(node, prefix = '') {
        let result = '';
        const keys = Object.keys(node).sort();
        
        for (let i = 0; i < keys.length; i++) {
            const key = keys[i];
            const isLast = i === keys.length - 1;
            const isDir = node[key] !== null;
            
            result += prefix;
            result += isLast ? '└── ' : '├── ';
            result += key;
            if (isDir) result += '/';
            result += '\n';
            
            if (isDir) {
                const newPrefix = prefix + (isLast ? '    ' : '│   ');
                result += renderTree(node[key], newPrefix);
            }
        }
        return result;
    }
    
    return '```\n' + renderTree(tree) + '```';
}

// Convert to markdown
export function formatToMarkdown(repoData) {
    const { repoInfo, files, fetchedAt } = repoData;
    
    let markdown = `# Repository: ${repoInfo.fullName}\n\n`;
    markdown += `## Metadata\n`;
    markdown += `- **Fetched at:** ${fetchedAt}\n`;
    markdown += `- **Default branch:** ${repoInfo.defaultBranch}\n`;
    markdown += `- **Total files:** ${repoInfo.totalFiles}\n`;
    markdown += `- **Total size:** ${(repoInfo.totalSizeKB / 1024).toFixed(2)} MB\n`;
    markdown += `- **Total characters:** ${repoInfo.totalChars.toLocaleString()}\n`;
    
    if (repoInfo.description) {
        markdown += `- **Description:** ${repoInfo.description}\n`;
    }
    
    markdown += `\n---\n\n`;
    markdown += `## 📁 Directory Structure\n\n`;
    markdown += generateDirectoryTree(files);
    markdown += `\n---\n\n`;
    markdown += `## 📄 File Contents\n\n`;
    
    const sortedFiles = [...files].sort((a, b) => a.path.localeCompare(b.path));
    
    for (const file of sortedFiles) {
        if (file.content) {
            markdown += `### File: \`${file.path}\`\n\n`;
            markdown += `\`\`\`${getLanguageFromPath(file.path)}\n`;
            markdown += file.content;
            if (!file.content.endsWith('\n')) markdown += '\n';
            markdown += `\`\`\`\n\n`;
        }
    }
    
    markdown += `---\n`;
    markdown += `*Generated by RepoCodeBridge | AI-Readable Format*`;
    
    return markdown;
}

// JSON format
export function formatToJSON(repoData) {
    const { repoInfo, files, fetchedAt } = repoData;
    
    const output = {
        metadata: {
            repository: repoInfo.fullName,
            fetchedAt: fetchedAt,
            defaultBranch: repoInfo.defaultBranch,
            totalFiles: repoInfo.totalFiles,
            totalSizeMB: (repoInfo.totalSizeKB / 1024).toFixed(2),
            description: repoInfo.description || null,
        },
        structure: {},
        files: {},
    };
    
    for (const file of files) {
        output.files[file.path] = {
            content: file.content,
            size: file.size,
            language: getLanguageFromPath(file.path),
        };
        
        const parts = file.path.split('/');
        let current = output.structure;
        for (let i = 0; i < parts.length; i++) {
            const part = parts[i];
            if (i === parts.length - 1) {
                current[part] = 'file';
            } else {
                if (!current[part]) current[part] = {};
                current = current[part];
            }
        }
    }
    
    return JSON.stringify(output, null, 2);
}